### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by jenkoian** [alleyinteractive/wp-seo#115]
It's been quite a while since 0.13 was tagged, how about a new tag? Also ready for 1.0? If not can you add a branch alias for dev-master? https://getcomposer.org/doc/articles/aliases.md#branch-alias

**Comment by unitof** [comment]
Would love to know if y'all consider this project archived and as-is, or still solid & supported (however you define "supported"). Thanks!

**Comment by dlh01** [comment]
We don't currently have plans to add features to the plugin, but we do have clients that use it, so there's always a chance of a fix or adjustment being made to support them.

An 0.14 was never tagged in part because the commits since 0.13 contain breaking changes, which there was never a resolution about. See #104. 

I suppose we could tag an 0.14 anyway and mark it clearly as breaking. Or tag it 1.0 to deliver a degree of closure. Thoughts @mboynes?

**Comment by mboynes** [comment]
@dlh01 no objections from me in tagging 1.0. go for it!

**Comment by dlh01** [comment]
Tagged: https://github.com/alleyinteractive/wp-seo/releases/tag/v1.0.0

Thanks @jenkoian, and thanks for the prompt @unitof.
